### ISSUE TITLE
токены лучше не комитить

### ISSUE THREAD

**Issue by TovarischSukhov** [Gramst/lessons#2]
https://github.com/Gramst/lessons/blob/38a2dbf6f9809eec294913f05cc1b1cad1eca924/Bot_settings.py#L1
как думаешь, почему?

**Comment by Gramst** [comment]
А почему... ну это как-бы ключ от бота + там всякие личные данные лучше не выкладывать на всеобщее обозрение

**Comment by TovarischSukhov** [comment]
что почему? почему не выкладывать?
потому что имея ключ от бота в него можно писать и твои пользователи будут думать, что это ты. Таким образом периодически воруют популярных (или не очень) ботов для запуска рекламных рассылок.
ну а персональные данные просто лучше не коммитить - персональные все таки, а тут все на всеобщем обозрении

**Comment by Gramst** [comment]
Я это и имел в виду) Конечно теперь я вижу что фраза  "ну это как-бы ключ от бота" была малоинформативной)
